<?php
	$title = '用户登录';
	$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('member', array('action' => 'SignIn')));
$form->prepare();

//$pubKey = '6Lfgmt4SAAAAAKXBItafl4SCniGWXuGKYkEDrsBK';
//$privKey = '6Lfgmt4SAAAAAH2W9NGd5AGDMwK2L3XANWmOB_Aj';
//$recaptcha = new ZendService\ReCaptcha\ReCaptcha($pubKey, $privKey);
$recaptcha = new ZendService\ReCaptcha\ReCaptcha(PUBKEY, PRIVKEY);

echo $this->form()->openTag($form);
?>

<table>
  <tr>
    <td></td>
    <td><?php echo $this->formHidden($form->get('id')); ?></td>
  </tr>
  <tr>
    <td>用户名: </td>
    <td><?php echo $this->formRow($form->get('memberName')); ?></td>
  </tr>
  <tr>
    <td>密码: </td>
    <td><?php echo $this->formRow($form->get('memberPasswd')); ?></td>
  </tr>
  <tr>
    <td>验证码: </td>
    <td><?php echo $this->formRow($form->get('captcha'));
			  //echo $recaptcha->getHTML();
			  ?></td>
  </tr>
  <tr>
    <td></td>
    <td><?php echo $this->formSubmit($form->get('submit')); ?></td>
  </tr>
</table>

<?php 
	echo $this->form()->closeTag();
	
?>
	
